name: Deploy Node App

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
            - name: Build Docker Image
              run: docker build -t akara840/mern-app-backend .
            - name: Publish Image to docker hub
              run: docker push akara840/mern-app-backend:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull Image from the docker hub
              run: docker pull akara840/mern-app-backend:latest
            - name: Delete old container
              run: docker rm -f mern-app-backend-container
            - name: Run Docker container
              run: docker run -d -p 5050:5050 --name mern-app-backend-container -e ATLAS_URI=${{secrets.ATLAS_URI}} akara840/mern-app-backend